version: '3.7'
services:

  php-fpm:
    image: localhost/template-php-fpm:latest
    restart: always
    container_name: template-php-fpm
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www/html

  nginx:
    image: localhost/template-nginx:latest
    restart: always
    container_name: template-nginx
    ports:
      - ${APP_WEB_PORT}:80
    environment:
      PHP_UPSTREAM_CONTAINER: php-fpm
      PHP_UPSTREAM_PORT: 9000
    depends_on:
      - php-fpm
    volumes:
      - ./web:/var/www/html/web

  mariadb:
    image: mariadb:10.6.14
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]

volumes:
    mysql: